apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-app
  labels:
    app: myweb-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myweb-app
  template:
    metadata:
      labels:
        app: myweb-app
    spec:
      containers:
        - name: myweb-app
          image: 177734118185.dkr.ecr.eu-west-2.amazonaws.com/mywebapp:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 80
