apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-app
  labels:
    app: myweb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb-app
  template:
    metadata:
      labels:
        app: myweb-app
    spec:
      containers:
        - name: myweb-app
          image: 274127640471.dkr.ecr.us-east-1.amazonaws.com/myweb-app:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080